### ISSUE TITLE
Create a simple page to call the API

### ISSUE THREAD

**Issue by jshales4** [rileyamos/LearnTheNews#11]
Put on S3, create an IAM user for the front end. API will only allow requests from IAM user. 
Make an IAM user that can only access the bucket that will have the webpage.

**Comment by rileyamos** [comment]
If you want - Since the UI is in a good state, does it make sense to set up an IAM user for me personally (giving me access to the single bucket) and then I can push to the bucket? From there we can create another IAM user for the bucket itself and configure the API access.

**Comment by jshales4** [comment]
Closing, we no longer need to do this
