### ISSUE TITLE
Better Understand Text Length limitations of Comprehend

### ISSUE THREAD

**Issue by jshales4** [rileyamos/LearnTheNews#18]
Can we convert UTF8 to ASCII and send that to Comprehend?

**Comment by rileyamos** [comment]
I may have misread the documentation initially. UTF-8 looks like it is required.

https://docs.aws.amazon.com/comprehend/latest/dg/guidelines-and-limits.html

**Comment by jshales4** [comment]
We are now truncating at 5000 bytes
