### ISSUE TITLE
Add Method to detect Word Frequency

### ISSUE THREAD

**Issue by rileyamos** [rileyamos/LearnTheNews#3]
<img width="240" alt="screen shot 2018-03-08 at 8 22 29 pm" src="https://user-images.githubusercontent.com/7213342/37190424-77c2ee34-230e-11e8-9210-0daacd829db5.png">

We need to analyze the article and pull the most frequently used words. Be sure to not include words like "the", "it", etc.

**Comment by rileyamos** [comment]
**Here is my first pass:**
https://gist.github.com/rileyamos/31cbaf37c2fee79cb8588805005bfe35

**Comment by jshales4** [comment]
Integrated into the API and displayed in JSON result
