### ISSUE TITLE
Vet Sources

### ISSUE THREAD

**Issue by jshales4** [rileyamos/LearnTheNews#7]
Determine if we are using the best sources available with sensical descriptions (EX: BBC Radio gives a nonsense description and title which muddies analysis).

**Comment by rileyamos** [comment]
Here is a starter list. All of these appear to have clean data feeds. Let's start here and update as we see fit.

`$news-outlets:
  abc-news,
  al-jezeera-english,
  axios,
  buzzfeed,
  breitbart-news,
  bbc-news,
  cbs-news,
  cnbc,
  cnn,
  daily-mail,
  fox-news,
  msnbc,
  nbc-news,
  the-hill,
  the-huffington-post,
  the-guardian-uk,
  the-new-york-times,
  the-washington-post,
  the-wall-street-journal,
  usa-today;`

**Comment by jshales4** [comment]
Updated the list, we can continue to explore and fine tune this but closing for now.
